spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://127.0.0.1:3306/backend_project_02?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true"
    username: root
    password: 1234
    jpa:
      jpa:
        database: mysql
        hibernate.ddl-auto: none
        show-sql: true



